version: '3.8'

services:
  postgres_db:
    image: postgres:17.0
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME} 
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - micro_network

  micro_auth_user:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: micro_auth_user
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - postgres_db
    environment:
      DATABASE_HOST: ${DB_HOST}
      DATABASE_PORT: ${DB_PORT}
      DATABASE_USER: ${POSTGRES_USER}
      DATABASE_PASSWORD: ${POSTGRES_PASSWORD}
      DATABASE_NAME: ${DATABASE_NAME}
    networks:
      - micro_network

networks:
  micro_network: {}

volumes:
  postgres_data:
